NVTI_SGP/Controllers/ProfessoresController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using NVTI_SGP.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace NVTI_SGP.Controllers
{
    public class ProfessoresController : Controller
    {
        private readonly ILogger<ProfessoresController> _logger;
        public IActionResult Professores()
        {
            ViewBag.Professores = ListarProfessores();
            return View();
        }
        private IConfiguration Configuration { get; set; }
        public ProfessoresController(IConfiguration iConfig)
        {
            Configuration = iConfig;
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }













        public IActionResult Cadastro(int id)
        {
            ViewBag.Professor = GetProfessor(id);
            return View();
        }
        public List<Professor> ListarProfessores()
        {
            List<Professor> professores = new List<Professor>();
            using (var conn = new SqlConnection(Configuration.GetSection("ConnectionStrings").GetSection("NVTI").Value))
            {
                conn.Open();
                SqlCommand cmd = new SqlCommand("SELECT id, nome FROM nvt_professores", conn);
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    professores.Add(new Professor()
                    {
                        ID = (int)dr["id"],
                        Nome = (string)dr["nome"]
                    });
                }
                conn.Close();
            }
            return professores;
        }
        public Professor GetProfessor(int id)
        {
            Professor professor = new Professor();
            using (var conn = new SqlConnection(Configuration.GetSection("ConnectionStrings").GetSection("NVTI").Value))
            {
                conn.Open();
                SqlCommand cmd = new SqlCommand("SELECT id, nome FROM nvt_professores WHERE id = "+id, conn);
                SqlDataReader dr = cmd.ExecuteReader();
                if (dr.Read())
                {
                    professor = new Professor()
                    {
                        ID = (int)dr["id"],
                        Nome = (string)dr["nome"]
                    };
                }
                conn.Close();
            }
            return professor;
        }


        [HttpPost]
        public void Salvar(Professor professor)
        {
            string sql = "INSERT INTO nvt_professores (nome) VALUES (@nome)";
            if (professor.ID > 0) sql = "UPDATE nvt_professores SET nome = @nome WHERE id = @id";
            using (var conn = new SqlConnection(Configuration.GetSection("ConnectionStrings").GetSection("NVTI").Value))
            {
                conn.Open();
                SqlTransaction transacao = conn.BeginTransaction(IsolationLevel.ReadCommitted);
                try
                {
                    using (var command = new SqlCommand(sql, conn, transacao))
                    {
                        command.Parameters.AddWithValue("@id", professor.ID);
                        command.Parameters.AddWithValue("@nome", professor.Nome);
                        command.ExecuteNonQuery();
                        transacao.Commit();
                    }
                    conn.Close();
                    Response.Redirect("/Professores/Professores");
                }
                catch (SqlException erro)
                {
                    transacao.Rollback();
                    ViewBag.Erro = erro.Message;
                    Response.Redirect("/Home/Error");
                }
            }
        }
    }
}

NVTI_SGP/Views/Professores/Cadastro.cshtml
@{
    ViewData["Title"] = "Cadastro de Professor";
}
<div>
    <h1 class="display-4">@ViewData["Title"]</h1>
    <div class="row mb-3">
        <div class="col-12">
            <a class="btn btn-outline-info" asp-area="" asp-controller="Professores" asp-action="Professores">Voltar</a>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <form method="post" action="~/Professores/Salvar">
                <input type="hidden" name="id" value="@ViewBag.Professor.ID" />
                <label>Nome<br /><input name="nome" type="text" class="form-control" value="@ViewBag.Professor.Nome" />
                </label>
                <div class="my-3 pt-3 border-top">
                    <button class="btn btn-outline-primary">Salvar</button>
                    <a class="btn btn-outline-info" asp-area="" asp-controller="Professores" asp-action="Professores">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>

NVTI_SGP/Views/Professores/Professores.cshtml
@{
    ViewData["Title"] = "Professores";
}
<div>
    <div class="row mb-3">
        <div class="col-8">
            <h1 class="display-4">@ViewData["Title"]</h1>
        </div>
        <div class="col-4 text-right">
            <a class="btn btn-outline-info" asp-area="" asp-controller="Professores" asp-action="Cadastro">Novo professor</a>
        </div>
    </div>
    @if (ViewBag.Professores.Count > 0)
    {
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th class="text-right" style="width:74px;">#</th>
                    <th>Nome</th>
                    <th style="width:74px;"></th>
                </tr>
            </thead>
            <tbody>
                @{
                    foreach (Professor x in ViewBag.Professores)
                    {
                        <tr>
                            <td class="text-right" style="width:74px;">@x.ID</td>
                            <td>@x.Nome</td>
                            <td class="p-2" style="width:74px;"><a href="~/Professores/Cadastro/@x.ID" class="btn btn-outline-info">Alterar</a></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    }
    else
    {
        <div class="alert alert-warning" role="alert">Nenhum professor encontrado</div>
    }
</div>